### PR TITLE
Upgrade to nette 3

### PR DESCRIPTION
**Pull request by h4kuna**
- used Nette\Schema
- validate structure is copied from [nette\database](/nette/database/blob/master/src/Bridges/DatabaseDI/DatabaseExtension.php)
- the validation was missing for connect_timeout
- upgrade behavior with autowired
  - before you must set autowired like first in list of connections
  - now if second connection has autowired true that is accepted

### CODE REVIEW

**Comment by h4kuna** [comment]
I think these rules can be ignored
for phpstan:
```
Parameter #1 $type of method Nette\DI\Definitions\ServiceDefinition::setType() expects string|null,  
         class-string<Forrest79\PhPgSql\Db\Connection>|Forrest79\PhPgSql\Db\Connection given.
```
and for phpsc
```
101 | ERROR | [ ] Use of numeric literator separator is required.
     |       |     (SlevomatCodingStandard.Numbers.RequireNumericLiteralSeparator.RequiredNumericLiteralSeparator)
```
for phpcs i am not sure what they mean? If they mean [this](https://wiki.php.net/rfc/numeric_literal_separator)? This is not useable for older php version.

**Comment by forrest79** [comment]
ad CS) I'm disabling this on all projects :-) I don't like numeric literator separator - so yes, this could be ignored.

ad phpstan) I'm not looking to the source code right now, but `setType() expects string|null` expects `string` and get `class-string<Forrest79\PhPgSql\Db\Connection>` - that's ok or `Forrest79\PhPgSql\Db\Connection` - that's a little bit confusing? Why object?

**Comment by h4kuna** [comment]
I think, phpstan know string is specificated like **class-string** and want to define to phpdoc. But setType is method from Nette\DI\Definitions\ServiceDefinition.

**Comment by forrest79** [comment]
Thanks for this PR.

For the PHPStan error, I'm ok with:

```php
\assert(\is_string($connectionType));
```

Variable is string, so for me this make sence and PHPStan is also OK with this :-) I was confused, why is PHPStan detecting `$connectionType` as object, when it's declared always only as `string` (`class-string`), I think that's because of  this line `is_subclass_of($connectionType, PhPgSql\Db\Connection::class)`.

**Comment by h4kuna** [comment]
PR is ready

**Comment by forrest79** [comment]
Thanks. One last question. Is it possible to do Nette extension compatible with Nette 3 and Nette 2.4 in the same time?

**Comment by h4kuna** [comment]
No, you must keep two classes.

**Comment by h4kuna** [comment]
I update it, now exists one class and support nette 3.0 and 2.4. But tests check only 3.0.

phpcs has note 'Function method_exists() should be referenced via a fully qualified name.'
'SlevomatCodingStandard.Namespaces.FullyQualifiedGlobalFunctions.NonFullyQualified'

If i used Nette\DI\CompilerExtension::class is it fully qualified name? I didn't use string but constatnt.

Are you agree if i ignore this rule?

**Comment by forrest79** [comment]
Thanks a lot for your work. I like this solution. I created copy of your fork to local `h4kuna-nette3` branch with CS fixies. With this, I think it's ok.

**Comment by h4kuna** [comment]
Update from master

**Comment by h4kuna** [comment]
I made two commits
in first case I thought, the order of options in neon is superior to the order from extension, the opposite is true

in second commit i modify test which in this moment throw exception, because a member cannot set second connection like autowired

**Comment by forrest79** [comment]
Thanks, can you squash it and rebase to the master?

Ad failing test) I'm not sure, if this is an error. When you have more connections, the first is marked as autowired (the same is, if you have just one connection). When you want the second as autowired, set the first `autowired: false`. This behavior is taken from `Nette\Database` extension.

I'm OK with this. But we can do it better - do two iterations. First to determine, if there is only one `autowired: true`. If there is more than one, throw an exception, where there is none, set `autowired: true` to the first connection and than do a second iteration with `setupDatabase()`. I'm also OK with this solution, if you want to do this in a better way :-)

**Comment by h4kuna** [comment]
I thinking two iterations too. I made commit.

**Pull request merged**
